language: node_js

node_js:
  - "14.16"
  - "13"
  - "12"
  - "11"
  - "10.15"

before_script:
  - npm install

script:
  - npm test

notifications:
  emails:
    - tomk79@gmail.com
  on_success: always
  on_failure: always
